# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - develop

jobs:

  build & deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@v2
    - name: Setup Node version
      uses: actions/setup-node@v3
      with:
        node-version: 18.2.0
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - name: Add the private SSH key to the ssh-agent
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p ~/.ssh
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: Deploy build on VPS
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        scp -P ${{ secrets.VPS_SSH_PORT }} -o StrictHostKeyChecking=no -r build/* root@${{ secrets.VPS_IP_ADDRESS }}:/var/www/time-table.pp.ua/html
        ssh -o StrictHostKeyChecking=no root@${{ secrets.VPS_IP_ADDRESS }} -p ${{ secrets.VPS_SSH_PORT }} << 'ENDSSH'
          systemctl restart nginx
        ENDSSH